///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SomeRootEntityDataData {
/*
{
  "id": 1011,
  "tax_id": "0013",
  "tax_name": "税目AA",
  "tax_rate": 0.211,
  "edit_time": "2021-06-03"
}
*/

  int? id;
  String? taxId;
  String? taxName;
  double? taxRate;
  String? editTime;

  SomeRootEntityDataData({
    this.id,
    this.taxId,
    this.taxName,
    this.taxRate,
    this.editTime,
  });
  SomeRootEntityDataData.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    taxId = json["tax_id"]?.toString();
    taxName = json["tax_name"]?.toString();
    taxRate = json["tax_rate"]?.toDouble();
    editTime = json["edit_time"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["tax_id"] = taxId;
    data["tax_name"] = taxName;
    data["tax_rate"] = taxRate;
    data["edit_time"] = editTime;
    return data;
  }
}

class SomeRootEntityData {
/*
{
  "code": 0,
  "success": true,
  "data": [
    {
      "id": 1011,
      "tax_id": "0013",
      "tax_name": "税目AA",
      "tax_rate": 0.211,
      "edit_time": "2021-06-03"
    }
  ]
}
*/

  int? code;
  bool? success;
  List<SomeRootEntityDataData?>? data;

  SomeRootEntityData({
    this.code,
    this.success,
    this.data,
  });
  SomeRootEntityData.fromJson(Map<String, dynamic> json) {
    code = json["code"]?.toInt();
    success = json["success"];
    if (json["data"] != null) {
      final v = json["data"];
      final arr0 = <SomeRootEntityDataData>[];
      v.forEach((v) {
        arr0.add(SomeRootEntityDataData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["code"] = code;
    data["success"] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["data"] = arr0;
    }
    return data;
  }
}

class SomeRootEntity {
/*
{
  "code": 0,
  "data": {
    "code": 0,
    "success": true,
    "data": [
      {
        "id": 1011,
        "tax_id": "0013",
        "tax_name": "税目AA",
        "tax_rate": 0.211,
        "edit_time": "2021-06-03"
      }
    ]
  },
  "message": ""
}
*/

  int? code;
  SomeRootEntityData? data;
  String? message;

  SomeRootEntity({
    this.code,
    this.data,
    this.message,
  });
  SomeRootEntity.fromJson(Map<String, dynamic> json) {
    code = json["code"]?.toInt();
    data = (json["data"] != null) ? SomeRootEntityData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["code"] = code;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
